In [168]:
import numpy as np

# Print out the dimension (number of axes), shape, size and the datatype of the matrix A

In [23]:
A = np.arange(1, 16).reshape(3,5)

In [19]:
print("Axes:", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Datatype:", A.dtype)

Axes: 2
Shape: (3, 5)
Size: 15
Datatype: int32


# Do the following computations on the matrices B and C:
Elementwise subtraction.
Elementwise multiplication.
Matrix multiplication (by default you should use the @ operator).

In [22]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [38]:
elementwise_subtraction = B - C
print("Elementwise_subtraction")
print(elementwise_subtraction)

elementwise_multiplication = B * C
print("Elementwise subtraction")
print(elementwise_multiplication)

matrix_multiplication = B @ C
print("Elementwise multiplication")
print(matrix_multiplication)

Elementwise_subtraction
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Elementwise subtraction
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
Elementwise multiplication
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


# Do the following calculations on the matrix:
Exponentiate each number elementwise (use the np.exp function).

Calculate the minimum value in the whole matrix.

Calculcate the minimum value in each row.

Calculcate the minimum value in each column.

Find the index value for the minimum value in the whole matrix (hint: use np.argmin).

Find the index value for the minimum value in each row (hint: use np.argmin).

Calculate the sum for all elements.

Calculate the mean for each column.

Calculate the median for each column.

In [45]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
Exponentiate_B = np.exp(B)
print(Exponentiate_B)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [53]:
Min_B = np.min(B)
print(Min_B)

1


In [55]:
Min_value_per_row = np.min(B, axis = 1)

In [57]:
print(Min_value_per_row)

[1 4 7]


In [63]:
Min_value_per_column_row = np.min(B, axis = 0)
print(Min_value_per_column_row)

[1 2 3]


In [68]:
Min_value_index = np.argmin(B)
print(Min_value_index)

0


In [72]:
Min_value_index_per_row = np.argmin(B, axis = 1)
print(Min_value_index_per_row)

[0 0 0]


In [78]:
All_elements_sum = np.sum(B)
print(All_elements_sum)

45


In [88]:
Mean_each_column = np.mean(B, axis = 0)
print(Mean_each_column)

[4. 5. 6.]


In [90]:
Median_each_column = np.median(B, axis = 0)
print(Median_each_column)

[4. 5. 6.]


# What does it mean when you provide fewer indices than axes when slicing? See example below.

In [95]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [97]:
A[1]

array([ 6,  7,  8,  9, 10])

It means we get the elements that are on the provided index or indexes since numpy assumes with a provided index in this way that we want all the values that is on that row. And the elements that are not in those indexes or on different index not provided are being left out and not shown in the result. In this example we have 3 indexes going from 0 to 2. 0, 1, 2. And the index we are printing is 1. So index 0 and 2 are being left out and we get all the numbers only in index 1 because numpy again assumes we want all the elements on that index. So having fewer index than axes means we get a slice of the array on certain index or indexes with all the elements.

# Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array elementwise, how would you do that?

In [25]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [27]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [29]:
for i in np.nditer(A):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [31]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [42]:
Explain what the code below does. More specifically, b has three axes - what does this mean?
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

Object `mean` not found.
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


a = np.arange(30) Prints a 1D array with the values from 0 to 29 having 30 as it's limit number.
b = a.reshape((2, 3, -1)) This code reshapes the 'a' function, making it a 3D array. By having number 2 as first dimension telling how many blocks the shape is gonna be. Number 3 telling the second dimension, how many rows each block is gonna have. The third dimension -1 tells numpy to calculate the dimension to fit based of the amount of elements we have, doing the work for us. If we wanna see it happen mathematically in this example we can take all the elements of the function 30 and divide it by rows. 30/6 and see that the answer is 5. Making each row contain 5 elements as we see in the results.
So b having three axes means that function b has a collection of blocks or you can say collection of 2D arrays, it contains more than 1 2D array. Which then tells us and means that b is a 3D array.

Chapter 2, exercise 1-3

In [49]:
A = np.array([[2, 1, -1],
              [1, -1, 1]])

B = np.array([[4, -2, 1],
              [2, -4, -2]])

C = np.array([[1, 2],
              [2, 1]])

D = np.array([[3, 4],
              [4, 3]])

E = np.array([[1],
              [2]])

In [51]:
B_minus_2A = B - 2 * A
print(B_minus_2A)

[[ 0 -4  3]
 [ 0 -2 -4]]


In [59]:
C3_minus_E = 3 * C - E
print(C3_minus_E) #Not defined initially, but with broadcasting it works.

[[2 5]
 [4 1]]


In [170]:
A_times_C = A @ C
print(A_times_c) #Not defined

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [75]:
C_times_D = C @ D
print(C_times_D)

[[11 10]
 [10 11]]


In [73]:
C_times_B = C @ B
print(C_times_B)

[[  8 -10  -3]
 [ 10  -8   0]]


In [79]:
A = np.array([[1, 2],
              [2, 4]])

B = np.array([[2, 1],
              [1, 3]])

C = np.array([[4, 3],
              [0, 2]])

In [81]:
A_times_B = A @ B

In [83]:
print (A_times_B)

[[ 4  7]
 [ 8 14]]


In [91]:
A_times_C = A @ C
print(A_times_C)

[[ 4  7]
 [ 8 14]]


AB = AC is correct!

In [94]:
A = np.array([[1, 1, 1],
              [1, 2, 3],
              [1, 3, 4]])

D = np.array([[2, 0, 0],
              [0, 3, 0],
              [0, 0, 4]])

In [96]:
A_times_D = A @ D
print(A_times_D)

[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]


In [98]:
D_times_A = D @ A
print(D_times_A)

[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


Quiz on p.8, exercise 2.

In [101]:
A = np.array([[1, -1], 
              [-1, 1]])

B = np.array([[-1, 1], 
              [1, -1]])

In [103]:
A_times_B = A @ B
print(A_times_B)

[[-2  2]
 [ 2 -2]]


So a) is correct!

Chapter 6, exercise 1

In [107]:
A = np.array([[5, 6], 
              [4, 5]])

B = np.array([[6, 4], 
              [3, 3]])

In [111]:
A_inverse = np.linalg.inv(A)
print(A_inverse)

[[ 5. -6.]
 [-4.  5.]]


In [113]:
B_inverse = np.linalg.inv(B)
print(B_inverse)

[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


Quiz on p.15, exercise 3.

In [118]:
A = np.array([[2, 2], 
              [1, 2]])

In [122]:
A_inverse = np.linalg.inv(A)
print(A_inverse)

[[ 1.  -1. ]
 [-0.5  1. ]]


a) is correct!

Chapter 10, exercise 1.

In [132]:
A1 = np.array([[3, -7, -2],
               [-3, 5, 1],
               [6, -4, 0]])

In [141]:
B1 = np.array([-7, 5, 2])

In [143]:
a_solve = np.linalg.solve(A1, B1)
print(a_solve)

[ 3.  4. -6.]


X1 = 3 X2 = 4 x3 = -6

In [148]:
A2 = np.array([[1, -2 ,3],
               [-1, 3, -1],
               [2, -5, 5]])

In [152]:
B2 = np.array([1, -1, 1])

In [156]:
b_solve = np.linalg.solve(A2, B2)
print(b_solve)

[ 8.  2. -1.]


X1 = 8 X2 = 2 X3 = -1

Chapter 12 exercise 1

In [162]:
A = np.array([[3, -7, -2],
              [-3, 5, 1],
              [6, -4, 0]])

In [166]:
A_inverse = np.linalg.inv(A)
print(A_inverse)

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


# Chap2. Question 1.

Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [183]:
def add_mult_matrices(mat1, mat2, operation):
    if not isinstance(mat1, np.ndarray) or not isinstance(mat2, np.ndarray):
        raise valueError("Inputs must be of the type numpy.ndarray.")
    if operation == 'add':
        if mat1.shape != mat2.shape:
            raise ValuError("Matrices must be same size for addition!")
        return np.dot(mat1, mat2)
    elif operation == 'multiply':
        if mat1.shape[1] != mat2.shape[0]:
            raise ValueError("Amount of numbers in columns on the first matrix must equal amount of rows on the second matrix for multiplication to work.")
        return np.dot(mat1, mat2)

    else:
        raise ValueError("Operation must be either 'Add' or 'multiply'.")

In [185]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

In [199]:
try:
    multiply_matrices = add_mult_matrices(A, B.T, 'multiply')
    print(multiply_matrices)
except ValueError as e:
    print(e)


[[5 2]
 [7 4]]


In [201]:
try:
    add_matrices = add_mult_matrices(A, B, 'add')
    print(add_matrices)
except ValueError as e:
    print(e)

shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)


# Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [232]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [234]:
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [236]:
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


Since v2 is a slice of v1. Numpy decides that v2 is a view of v1 to save energy. Just a effecient way for numpy to work, to save resources and be effective. Neither v1 or v2 is a copy, v1 is its own database and v2 is just a slice of it connected to that database because its just a part of v1. We see it by printing them both out using .base, v1 has no base since it holds its own data, v1 is the numbers that you see i representing. And v2 has v1 as its base since its a part of it. But that doesnt make it a copy, it makes it a view, a view of v1. So changing v2 will change v1 since they are connected, v2 is a part of v1. So changing v2 is changing a part of v1. Thats why the 123 also pops up on v1 after adding it to v2.